// Date: 18/03/2016 16:43:13
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.railcraft_cos.common.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class CosSignalSemaphoreModel extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    
  /**
   * int rot should be -1 for lower quadrant, 0 for horizontal, 1 for upper quadrant signalling.
   */
  public CosSignalSemaphoreModel(int rot)
  {
    textureWidth = 32;
    textureHeight = 32;
    float rotation = 0.7853982F * (float)rot;
    float pointy;
    float pointx = 0F;
    if (rot == 1)
    {
    	pointy = 7F;
    	pointx = 2F;
    }
    else if (rot == 0)
    {
    	pointy = 12F;
    }
    else if (rot == -1)
    {
    	pointy = 17F;
    }
    else
    {
    	pointy = 12F;
    }
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 4, 14, 4);
      Shape1.setRotationPoint(-2F, 10F, -2F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 18);
      Shape2.addBox(0F, 0F, 0F, 7, 3, 1);
      Shape2.setRotationPoint(-6F+pointx, pointy, -3F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, rotation);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
